# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Uplift Backend CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: pgadmin
          POSTGRES_DB: uplift
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install yarn package manager
      run: npm install -g yarn
      
    - name: Install dependencies
      run: |
        yarn install
        
    - name: Run automated tests
      env:
        # The hostname used to communicate with the PostgreSQL service container
        POSTGRES_HOST: postgres
        POSTGRES_DB: uplift
        # The default PostgreSQL port
        POSTGRES_PORT: 5432
      run: |
        yarn test:cover
        
    - name: Upload coverage report to Codacy
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
